File buildLog = new File( basedir, 'build.log' )
assert buildLog.text.contains( '@Test test1 executed. constructorParameter value: test-value-294' )
assert buildLog.text.contains( '@Test test2 executed. constructorParameter value: test-value-294' )
assert buildLog.text.contains( '@Test test1 executed. constructorParameter value: test-value-168' )
assert buildLog.text.contains( '@Test test2 executed. constructorParameter value: test-value-168' )
assert 4 == buildLog.text.count( '@BeforeEach callback success' )
assert 4 == buildLog.text.count( '@AfterEach callback success' )
assert 1 == buildLog.text.count( '@BeforeAll callback success' )
assert 1 == buildLog.text.count( '@AfterAll callback success' )
